### ISSUE TITLE
Callback scheduling

### ISSUE THREAD

**Issue by Korijn** [fork-tongue/observ#18]
Should they be buffered? Should I provide event loop integration for various libs (i.e. asyncio, qt, etc)?

**Comment by ivoflipse** [comment]
I could imagine that if you make mutations inside a function, you'd expect everything in the function to complete before the observers respond. Otherwise I could expect some weird race conditions

**Comment by Korijn** [comment]
> I could imagine that if you make mutations inside a function, you'd expect everything in the function to complete before the observers respond. Otherwise I could expect some weird race conditions

Yeah, I am pretty sure it's possible to cause infinite loops right now, if you work with watchers only. Lazy computed variables, not so much.
