### ISSUE TITLE
Is it possible to watch all variables that are being observed?

### ISSUE THREAD

**Issue by Correct-Syntax** [fork-tongue/observ#24]
```python
from observ import computed, observe, watch


doc_state = observe({"selected": False, "pos": (0, 0)})

def my_callback(old, new):
    print(old, new)

w = watch(lambda: doc_state["selected"], callback=my_callback)

doc_state["selected"] = True
doc_state["selected"] = False
```
For example, in the code above, is it possible to watch both the ```selected``` and ```pos``` var without declaring a new ```watch``` statement? 

I guess I am trying to understand how multiple variables can be watched. My understanding is that something like the following is needed:

```python
from observ import computed, observe, watch


doc_state = observe({"selected": False, "pos": (0, 0)})

def my_selected_callback(old, new):
    print("selected: ", old, new)

def my_pos_callback(old, new):
    print("pos: ", old, new)

# setup the watchers
w1 = watch(lambda: doc_state["selected"], callback=my_selected_callback)
w2 = watch(lambda: doc_state["pos"], callback=my_pos_callback)

# do some stuff...

# set the sate
doc_state["selected"] = True
doc_state["selected"] = False

doc_state["pos"] = (3, 5)
```

**Comment by Korijn** [comment]
Well, sure! One option is to access both properties in the watcher expression by returning a tuple. Example:

```python
w = watch(lambda: (doc_state["selected"], doc_state['pos']), callback=my_callback)
```

You can pass arbitrary expressions to watchers. They're plain old functions (doesn't have to be a `lambda`) so you can access anything you want, use loops, etc!

**Comment by berendkleinhaneveld** [comment]
I suppose you could (mis)use a computed property for that, like so:

```python
from observ import computed, observe, watch

doc_state = observe({"selected": False, "pos": (0, 0)})

@computed
def multi():
	return {"select": doc_state["selected"], "position": doc_state["pos"]}

# setup the watchers
w = watch(multi, callback=lambda old, new: print(f"comp: {old}, {new}"))
w2 = watch(lambda: (doc_state["selected"], doc_state["pos"]), callback=lambda old, new: print(f"tuple: {old}, {new}"))

# do some stuff...

# set the sate
doc_state["selected"] = True
doc_state["selected"] = False
doc_state["pos"] = (3, 5)

```
While writing the example, I also figured that you can just construct a tuple in the lambda that is passed to the watch function...

Do any of these do what you had in mind?

**Comment by Correct-Syntax** [comment]
Thanks @Korijn and @berendkleinhaneveld for the lively "race to answer". 😄  

You've both been helpful with your answers, though I guess I am looking for a solution that would allow a **different callback for each variable that is watched.** 

How is that possible? Via the callback function itself somehow?

Indeed, I do plan to use this library to help in creating a real, stateful desktop application so the Qt example was helpful in clarifying some things in my mind -but I still am trying to get the idea of how things should work in a purely stateful way as I am more used to the MVC pattern (I also haven't done much with Vue.js, so I am not as familiar as I would be with the concepts of Vue...).

**Comment by Korijn** [comment]
> Thanks @Korijn and @berendkleinhaneveld for the lively "race to answer". 😄
> 
> You've both been helpful with your answers, though I guess I am looking for a solution that would allow a **different callback for each variable that is watched.**
> 
> How is that possible? Via the callback function itself somehow?

Well... the constraint is one callback for one watcher. So you would create a watcher for every callback you need, and set them up to listen to the variables that should trigger the callback.

Note that: you can still access the rest of the state (that you may not be listening to) as you usually would within a callback if you need to!

> Indeed, I do plan to use this library to help in creating a real, stateful desktop application so the Qt example was helpful in clarifying some things in my mind -but I still am trying to get the idea of how things should work in a purely stateful way as I am more used to the MVC pattern (I also haven't done much with Vue.js, so I am not as familiar as I would be with the concepts of Vue...).

Awesome! I hope your experience working with `observ` will be good!
